---
name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Install Project Dependencies
        run: |
          poetry install --only main,test

      - name: Run Unit Tests
        run: poetry run pytest --cov-report term --cov
        
  docker-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Build Docker Image
        run: |
          docker build --target test-results -t image-test .
        shell: bash  
  
  code-quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Install Project Dependencies
        run: |
          poetry install --only main,code-quality

      - name: Formatter Check
        run: poetry run black --check .

      - name: Import Order Check
        run: poetry run isort --check-only --diff .

      - name: Linter Check
        run: poetry run flake8 .  
